<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function swtor_upgrade_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

abstract class SwtorMigration extends Migration {
  protected $source_db = 'swtor_d6';
  protected $source_path = '/home/cableman/source/off-work/swtor_d6';

  public function __construct() {
    parent::__construct(MigrateGroup::getInstance('swtor'));
  }
}

/**
 * Helper function that mappes a given uid to a source uid, so content can
 * be upgrade with the correct user information.
 *
 * @param type $source_db
 * @param type $uid
 * @return type
 */
function swtor_upgrade_map_uid($source_db, $uid) {
  $uid_query = db_select($source_db . '.users', 'su')
               ->condition('su.uid', $uid);
  $uid_query->join('users', 'u', 'su.name = u.name');
  $uid_query->addField('u', 'uid');
  return $uid_query->execute()->fetchField();
}