<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function swtor_upgrade_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

abstract class SwtorMigration extends Migration {
  protected $source_db = 'swtor_d6';

  public function __construct() {
    parent::__construct();
  }
}